site_name: OVITO用户手册中文翻译

site_description: OVITO用户手册中文翻译
site_author: 抓根

theme:
    name: 'readthedocs'
    favicon: 'img/Dragon.ico'

nav:
  - Home: index.md
  - 用法: 
      - 导入数据: 用法/导入数据.md
      - 视角: 用法/视角.md
      - 粒子性质: 用法/粒子属性.md
      - 修正通道: 用法/修正通道.md
      - 渲染图像及视频: 用法/渲染图像及视频.md
      - 杂项: 用法/杂项.md
      - 导出数据: 用法/导出数据.md
      - Python脚本: 用法/Python脚本.md
      - 动画系统: 用法/动画系统.md
  - 操作指南: 
      - 半透明粒子: 操作指南/半透明粒子.md
      - 标记原子的可视化操作: 操作指南/标记原子的可视化操作.md
      - 可视化粒子轨迹: 操作指南/可视化粒子轨迹.md
      - 视角上添加缩放栏: 操作指南/视角上添加缩放栏.md
      - 非球形粒子: 操作指南/非球形粒子.md
  - 参考: 
      - 修正器:
        - 仿射变换: 参考/修正器/仿射变换.md
        - 环境光屏蔽: 参考/修正器/环境光屏蔽.md
        - 分配颜色: 参考/修正器/分配颜色.md
        - 储存与减少: 参考/修正器/储存与减少.md
        - 键角分析: 参考/修正器/键角分析.md
        - 中心对称参数: 参考/修正器/中心对称参数.md
        - 清空选项: 参考/修正器/清空选项.md
        - 聚类分析: 参考/修正器/聚类分析.md
        - 颜色编码: 参考/修正器/颜色编码.md
        - 联结粒子设置: 参考/修正器/联结粒子设置.md
        - 通用临近分析: 参考/修正器/通用临近分析.md
        - 计算键长: 参考/修正器/计算键长.md
        - 计算属性: 参考/修正器/计算属性.md
        - 构造网格表面: 参考/修正器/构造网格表面.md
        - 坐标分析: 参考/修正器/坐标分析.md
        - 坐标多面体: 参考/修正器/坐标多面体.md
        - 创建化学键: 参考/修正器/创建化学键.md
        - 创建等值面: 参考/修正器/创建等值面.md
        - 删除所选粒子: 参考/修正器/删除所选粒子.md
        - 位错（DXA）分析: 参考/修正器/位错（DXA）分析.md
        - 位移矢量: 参考/修正器/位移矢量.md
        - 弹性应变计算: 参考/修正器/弹性应变计算.md
        - 展开选择: 参考/修正器/展开选择.md
        - 表达式选择: 参考/修正器/表达式选择.md
        - 冻结性质: 参考/修正器/冻结性质.md
        - 直方图: 参考/修正器/直方图.md
        - 识别钻石结构: 参考/修正器/识别钻石结构.md
        - 反选: 参考/修正器/反选.md
        - 加载轨道: 参考/修正器/加载轨道.md
        - 手动选择: 参考/修正器/手动选择.md
        - 多面体模板匹配: 参考/修正器/多面体模板匹配.md
        - Python脚本修改器: 参考/修正器/Python脚本修改器.md
        - 散点图: 参考/修正器/散点图.md
        - 选择粒子种类: 参考/修正器/选择粒子种类.md
        - 显示周期性图像: 参考/修正器/显示周期性图像.md
        - 切片: 参考/修正器/切片.md
        - 泰森多边形法分析: 参考/修正器/泰森多边形法分析.md
        - 泰森多边形拓扑分析: 参考/修正器/泰森多边形拓扑分析.md
        - 维格纳-赛兹缺陷分析: 参考/修正器/维格纳-赛兹缺陷分析.md
        - 在周期性边界环绕: 参考/修正器/在周期性边界环绕.md
      - 修改器预设: 
      - 外部文件源: 
      - 显示对象: 
        - 键显示: 参考/显示对象/键显示.md
        - 粒子显示: 参考/显示对象/粒子显示.md
        - 表面网格显示: 参考/显示对象/表面网格显示.md
        - 向量显示: 参考/显示对象/向量显示.md
      - 视角:
        - 调整视角对话框: 参考/视角/调整视角对话框.md
        - 视角叠加: 参考/视角/视角叠加.md
      - 动画设置对话框: 参考/动画设置对话框.md
      - 粒子检测实用工具: 参考/粒子检测实用工具.md
      - 渲染:
        - 渲染设置: 参考/渲染/渲染设置.md
        - OpenGL渲染器: 参考/渲染/OpenGL渲染器.md
        - Tachyon渲染器: 参考/渲染/Tachyon渲染器.md
        - POV-Ray渲染器: 参考/渲染/POV-Ray渲染器.md
  - 开发者信息: 
    - 在Linux上构建OVITO: 开发者信息/在Linux上构建OVITO.md
    - 在Windows上构建OVITO: 开发者信息/在Windows上构建OVITO.md
    - 在MacOS上构建OVITO: 开发者信息/在MacOS上构建OVITO.md
  - 信用与许可: 


#http://127.0.0.1:8000/
#<script type="text/javascript" async
  #src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML">
#</script>
#<script type="text/x-mathjax-config">
#MathJax.Hub.Config({
  #tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
#});
#</script>